import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author matheus
 */
public final class mainMenu extends javax.swing.JFrame {

    Connection con = null;
    private DefaultTreeModel treeModel;
    
    public mainMenu() throws SQLException {
        initComponents();
        conectToDB("jdbc:postgresql://localhost/testdb", "postgres", "postgres");
        initializeDatabaseTree();

    }
    
    public void conectToDB(String url, String user, String password) throws SQLException
    {
        con = DriverManager.getConnection(url, user, password);
        DatabaseMetaData dbmt = con.getMetaData();
    }
    
    public void initializeDatabaseTree() throws SQLException
    {
        
        DefaultMutableTreeNode databases = new DefaultMutableTreeNode("Databases");
        treeModel = (DefaultTreeModel) databaseTree.getModel();
        treeModel.setRoot(databases);
        DatabaseMetaData metadata = con.getMetaData();

        ResultSet rs = metadata.getCatalogs();

        while(rs.next()){
            String database = rs.getString(1);
            DefaultMutableTreeNode dat = new DefaultMutableTreeNode(database);
            treeModel.insertNodeInto(dat, databases, 0);  
            DefaultMutableTreeNode table = new DefaultMutableTreeNode("Tables");
            DefaultMutableTreeNode view = new DefaultMutableTreeNode("Views");
            treeModel.insertNodeInto(view, dat, 0);
            treeModel.insertNodeInto(table, dat, 0);
            
            loadTables(table);
        }
    

    }

    
    private void loadTables(DefaultMutableTreeNode database) throws SQLException{
        DatabaseMetaData metadata = con.getMetaData();
        String[] t = {"TABLE"};
        ResultSet rs = metadata.getTables(null, null, "%", t);
        while(rs.next()){
            String tabname = rs.getString("TABLE_NAME");
            DefaultMutableTreeNode tab = new DefaultMutableTreeNode(tabname);
            treeModel.insertNodeInto(tab,database, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        databaseTree = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        insertQuery = new javax.swing.JTextArea();
        run = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(databaseTree);

        insertQuery.setColumns(20);
        insertQuery.setRows(5);
        jScrollPane3.setViewportView(insertQuery);

        run.setText("Run query!");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(run)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        System.out.println(this.insertQuery.getText());
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(this.insertQuery.getText());
            ResultSetMetaData rsmd = rs.getMetaData();
            
            int column = rsmd.getColumnCount();
            String[][] table = new String[11][column];
            for(int i = 0; i < column; i++)
            {
                table[0][i] = rsmd.getColumnName(i+1);
            }
            /*while (resultSet.next()) {
                for (int i = 1; i <= columnsNumber; i++) {
                    if (i > 1) System.out.print(",  ");
                    String columnValue = resultSet.getString(i);
                    System.out.print(columnValue + " " + rsmd.getColumnName(i));
                }
                System.out.println("");
            }*/
            
        } catch (SQLException ex) {
            System.out.println(ex);
            //Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainMenu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree databaseTree;
    private javax.swing.JTextArea insertQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton run;
    // End of variables declaration//GEN-END:variables
}
